### ISSUE TITLE
How to include b.v4 in the project 

### ISSUE THREAD

**Issue by jeanbauer** [FringeLabs/slush-fringe-react#11]
Testing the tool adding Bootstrap V.4 (typing '**yes**' in the CLI) does nothing.

Should not add the bootstrap and jquery to vendors or something?

Also, which process is the best to work adding another vendors? _e.g. fontawesome_

**Comment by vinnylinck** [comment]
I'll test that. BTW, I like the idea about adding something like fontawesome.

**Comment by vinnylinck** [comment]
the problem is not the code itself. The problem is the bootstrap. Initially, the boiler was built with bootstrap 4 alpha-2. But when running npm install, it installs alpha-3 and this version has a bug when importing bootstrap as a module.

I created ticket #13 for make it compatible with alpha-3 bootstrap, but for now, I`m thinking about forcing alpha-2 version of the package.
